server:
  port: 80

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://user-db:3306/users
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
