spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:PORT/DB_NAME
    username: changeMe
    password: changeMe
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80

